server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location ^~ /assets/ {
        try_files $uri =404;
        expires 1y;
    }

    location = /index.html {
        try_files $uri =404;
        expires epoch;
    }

    location / {
        try_files $uri $uri/ /index.html;
        expires epoch;
    }
}
